version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
            - ./domain.crt:/etc/ssl/certs/mycert.crt
            - ./domain.key:/etc/ssl/private/mycert.key
        ports:
            - 8000:80
            - 8443:443

    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootuser
            MYSQL_DATABASE: store
            MYSQL_USER: user
            MYSQL_PASSWORD: userpass
        ports:
            - "9906:3306"
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
      
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db